export default [
  {
    name  : 'dashboard',
    title : 'Dashboard',
    url   : '/cashplus/dashboard',
    icon  : 'icon-speedometer',
    access: '*',
  },
  {
    name  : 'upload-data',
    title : 'Upload Data',
    url   : '/cashplus/upload/data',
    icon  : 'icon-cloud-upload',
    access: '*',
  },
  {
    name    : 'all',
    title   : 'All Data',
    url     : 'javascript:;',
    icon    : 'icon-layers',
    access  : '*',
    children: [
      {
        name : 'sms-sent',
        title: 'SMS Sent',
        url  : '/cashplus/data/sms_sent',
        icon : '',
      },
      {
        name : 'landing-page',
        title: 'Landing Page',
        url  : '/cashplus/data/landing_page',
        icon : '',
      },
      {
        name : 'disbursement',
        title: 'Disbursement',
        url  : '/cashplus/data/disbursement',
        icon : '',
      },
      {
        name : 'submit-otp',
        title: 'Submit OTP',
        url  : '/cashplus/data/submit_otp',
        icon : '',
      },
      {
        name : 'sent-to-cimb',
        title: 'Send To CIMB',
        url  : '/cashplus/data/sentto',
        icon : '',
      },
      {
        name : 'approved',
        title: 'Approved',
        url  : '/cashplus/data/approve',
        icon : '',
      },
      {
        name : 'reject',
        title: 'Reject',
        url  : '/cashplus/data/reject',
        icon : '',
      },
    ],
  },
  {
    name  : 'download',
    title : 'Download',
    url   : '/cashplus/download/filter',
    icon  : 'icon-arrow-down-circle',
    access: '*',
  },
  {
    name  : 'downloaded',
    title : 'Downloaded',
    url   : '/cashplus/download/list',
    icon  : 'icon-arrow-down-circle',
    access: '*',
  },
  {
    name  : 'upload-result',
    title : 'Upload Result',
    url   : '/cashplus/upload/result',
    icon  : 'icon-arrow-up-circle',
    access: '*',
  },
  {
    name  : 'history',
    title : 'History SMS',
    url   : '/cashplus/history',
    icon  : 'icon-note',
    access: '*',
  },
  {
    name  : 'free-admin-fee',
    title : 'Free Admin Fee',
    url   : '/cashplus/adminfee',
    icon  : 'icon-star',
    access: '*',
  },
  {
    name  : 'users',
    title : 'Users',
    url   : '/cashplus/users',
    icon  : 'icon-people',
    access: '*',
  },
  {
    name  : 'activity-log',
    title : 'Activity Log',
    url   : '/cashplus/activity',
    icon  : 'icon-refresh',
    access: '*',
  },
]
