export default [
  {
    name  : 'dashboard',
    title : 'Dashboard',
    url   : '/dashboard',
    icon  : 'icon-speedometer',
    access: '*',
  },
  {
    name  : 'widget',
    title : 'Widget',
    url   : '/widgets',
    icon  : 'icon-cloud-upload',
    access: '*',
  },
  {
    name    : 'element',
    title   : 'Elements',
    url     : 'javascript:;',
    icon    : 'icon-layers',
    access  : '*',
    children: [
      {
        name : 'button',
        title: 'Button',
        url  : '/element/buttons',
        icon : '',
      },
      {
        name : 'alert',
        title: 'Alerts',
        url  : '/element/alert',
        icon : '',
      },
      {
        name : 'cards',
        title: 'Cards',
        url  : '/element/cards',
        icon : '',
      },
      {
        name : 'colors',
        title: 'Colors',
        url  : '/element/colors',
        icon : '',
      },
      {
        name : 'modals',
        title: 'Modals',
        url  : '/element/modals',
        icon : '',
      },
      {
        name : 'typography',
        title: 'Typography',
        url  : '/element/typography',
        icon : '',
      },
      {
        name : 'tabs-accordions',
        title: 'Tabs & Accordions',
        url  : '/element/tabs',
        icon : '',
      },
    ],
  },
  {
    name  : 'download',
    title : 'Download',
    url   : '/download/filter',
    icon  : 'icon-arrow-down-circle',
    access: '*',
  },
  {
    name  : 'downloaded',
    title : 'Downloaded',
    url   : '/download/list',
    icon  : 'icon-arrow-down-circle',
    access: '*',
  },
  {
    name  : 'upload-result',
    title : 'Upload Result',
    url   : '/upload/result',
    icon  : 'icon-arrow-up-circle',
    access: '*',
  },
  {
    name  : 'history',
    title : 'History SMS',
    url   : '/history',
    icon  : 'icon-note',
    access: '*',
  },
  {
    name  : 'free-admin-fee',
    title : 'Free Admin Fee',
    url   : '/adminfee',
    icon  : 'icon-star',
    access: '*',
  },
  {
    name  : 'users',
    title : 'Users',
    url   : '/users',
    icon  : 'icon-people',
    access: '*',
  },
  {
    name  : 'activity-log',
    title : 'Activity Log',
    url   : '/activity',
    icon  : 'icon-refresh',
    access: '*',
  },
]
